name: Build and Run

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - name: build Sender(MedicalDevice)
      run: g++ Sender\*.cpp -I mc3inc -L mc3lib -l jansson -l libxml2 -l mc3adll64 -l mc3adll64d -l mc3adv64 -l picxm -o sender
  
    # - name: run receiver locally
    #   run: cd Receiver && ./stor_scp.exe -p 6767 -s
          
    # - name: run Sender locally
    #   run: cd mc3lib && ./sender.exe MERGE_STORE_SCP -p 6767 
   
    - name: build senderTestApplication
      run: g++ SenderTest\*.cpp -I mc3inc -L mc3lib -l jansson -l libxml2 -l mc3adll64 -l mc3adll64d -l mc3adv64 -l picxm --coverage -o senderTestApp
   
    - name: move gcno to sender test dir
      run: move *.gcno SenderTest 
         
    # - name: run python script locally
    #   run: cd EmailSender && python filepolling.py

    - name: move senderTestApp to mc3lib
      run: move senderTestApp.exe mc3lib
    
    - name: cd into mc3lib to run sender
      run: cd mc3lib && ./senderTestApp.exe 

    - name: move .gcda files to sender test dir
      run:  move *.gcda SenderTest

    - name: sender coverage report
      run:  gcov -r SenderTest\*.cpp
